//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankManagementDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create account.
        /// </summary>
        public static string AccountInsertFailure {
            get {
                return ResourceManager.GetString("AccountInsertFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully.
        /// </summary>
        public static string AccountInsertSuccess {
            get {
                return ResourceManager.GetString("AccountInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number .
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be greater than 18.
        /// </summary>
        public static string AgeGreaterThan18 {
            get {
                return ResourceManager.GetString("AgeGreaterThan18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which field you want to edit?.
        /// </summary>
        public static string AskFieldToEdit {
            get {
                return ResourceManager.GetString("AskFieldToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE:     Rs. {0}.
        /// </summary>
        public static string BalanceDisplay {
            get {
                return ResourceManager.GetString("BalanceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not created. Please try again..
        /// </summary>
        public static string CardInsertFailure {
            get {
                return ResourceManager.GetString("CardInsertFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card created successfully. Save Card Number and Pin for later use..
        /// </summary>
        public static string CardInsertSuccess {
            get {
                return ResourceManager.GetString("CardInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card number does not exist. Please enter a valid card number to proceed.
        /// </summary>
        public static string CardNumberNotExist {
            get {
                return ResourceManager.GetString("CardNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. CREDIT CARD                     2.DEBIT CARD.
        /// </summary>
        public static string CardTypes {
            get {
                return ResourceManager.GetString("CardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card verification failed.
        /// </summary>
        public static string CardVerificationFailed {
            get {
                return ResourceManager.GetString("CardVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose account from the above list.
        /// </summary>
        public static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Account Type: .
        /// </summary>
        public static string ChooseAccountType {
            get {
                return ResourceManager.GetString("ChooseAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a different account number to transfer.
        /// </summary>
        public static string ChooseDifferentTransferAccount {
            get {
                return ResourceManager.GetString("ChooseDifferentTransferAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account to proceed.
        /// </summary>
        public static string ChooseFromAccountsList {
            get {
                return ResourceManager.GetString("ChooseFromAccountsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose only from the above listed options.
        /// </summary>
        public static string ChooseOnlyFromOptions {
            get {
                return ResourceManager.GetString("ChooseOnlyFromOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose mode of payment:.
        /// </summary>
        public static string ChoosePaymentMode {
            get {
                return ResourceManager.GetString("ChoosePaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase amount is greater than Available credit limit.
        /// </summary>
        public static string CreditLimitReached {
            get {
                return ResourceManager.GetString("CreditLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already has a debit card linked to it. Please choose a different account to link..
        /// </summary>
        public static string DebitCardLinkedError {
            get {
                return ResourceManager.GetString("DebitCardLinkedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit unsuccessful.
        /// </summary>
        public static string DepositFailure {
            get {
                return ResourceManager.GetString("DepositFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit of Rs.{0} is successful.
        /// </summary>
        public static string DepositSuccess {
            get {
                return ResourceManager.GetString("DepositSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nAccount Number: {0}\nType: {1}\nStatus: {2}.
        /// </summary>
        public static string DisplayAccount {
            get {
                return ResourceManager.GetString("DisplayAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nCard Type: {0}\nCard Number: {1}\nExpiry Month: {2}\nExpiry Year: {3}\n.
        /// </summary>
        public static string DisplayCard {
            get {
                return ResourceManager.GetString("DisplayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCardType: {0}\nTotalDueAmount: {1}\nCredit Limit: {2}\nCredit Points: {3}\n.
        /// </summary>
        public static string DisplayCreditCard {
            get {
                return ResourceManager.GetString("DisplayCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nMinimum Balance: {0}\n======================================\n.
        /// </summary>
        public static string DisplayCurrentAccount {
            get {
                return ResourceManager.GetString("DisplayCurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}\nAge: {1}\nEmail: {2}\nPhone: {3}\nLast Logged On: {4}.
        /// </summary>
        public static string DisplayCustomer {
            get {
                return ResourceManager.GetString("DisplayCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n ================== PROFILE ===================\n{0}\nNo. of Accounts: {1}\n\n ==============================================\n.
        /// </summary>
        public static string DisplayProfile {
            get {
                return ResourceManager.GetString("DisplayProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterestRate: {0}\n======================================\n.
        /// </summary>
        public static string DisplaySavingsAccount {
            get {
                return ResourceManager.GetString("DisplaySavingsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type: {0}\nTransaction Time: {1}\nDescription: {2}\nMode of Payment: {3}\nAmount: {4}\nBalance: {5}\n============================\n.
        /// </summary>
        public static string DisplayTransaction {
            get {
                return ResourceManager.GetString("DisplayTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should not be empty.
        /// </summary>
        public static string EmptyFieldError {
            get {
                return ResourceManager.GetString("EmptyFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your choice.
        /// </summary>
        public static string EnterChoice {
            get {
                return ResourceManager.GetString("EnterChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial deposit amount must be greater than Minimum Balance (Rs. {0}). Try again..
        /// </summary>
        public static string InitialDepositAmountWarning {
            get {
                return ResourceManager.GetString("InitialDepositAmountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Balance.
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest deposit of Rs. {0} has been initiated.
        /// </summary>
        public static string InterestDepositInitiated {
            get {
                return ResourceManager.GetString("InterestDepositInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account Number is invalid.
        /// </summary>
        public static string InvalidAccountNumber {
            get {
                return ResourceManager.GetString("InvalidAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid credit card number.
        /// </summary>
        public static string InvalidCreditCardNumber {
            get {
                return ResourceManager.GetString("InvalidCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        public static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid option. Try Again!.
        /// </summary>
        public static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid password. Password must be of length &gt; 8.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid 10-digit phone number.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid 4-digit pin.
        /// </summary>
        public static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need Debit Card for this account? Press &apos;y&apos; to accept or &apos;n&apos; to decline..
        /// </summary>
        public static string IsDebitCardRequired {
            get {
                return ResourceManager.GetString("IsDebitCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged out successfully.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Initial Deposit to complete account creation.
        /// </summary>
        public static string MakeInitialDeposit {
            get {
                return ResourceManager.GetString("MakeInitialDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been charged for not maintaining minimum balance.
        /// </summary>
        public static string MinimumBalanceCharged {
            get {
                return ResourceManager.GetString("MinimumBalanceCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. CASH                   2. DEBIT CARD.
        /// </summary>
        public static string ModeOfPayments {
            get {
                return ResourceManager.GetString("ModeOfPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pin.
        /// </summary>
        public static string NewPin {
            get {
                return ResourceManager.GetString("NewPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value to update.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards linked to your profile. Add cards to enable service..
        /// </summary>
        public static string NoCardsLinked {
            get {
                return ResourceManager.GetString("NoCardsLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function passed in delegate.
        /// </summary>
        public static string NullDelegateException {
            get {
                return ResourceManager.GetString("NullDelegateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b \b.
        /// </summary>
        public static string PasswordBackspace {
            get {
                return ResourceManager.GetString("PasswordBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string PasswordMask {
            get {
                return ResourceManager.GetString("PasswordMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not matching. Try again.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed.
        /// </summary>
        public static string PaymentFailure {
            get {
                return ResourceManager.GetString("PaymentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mode of payment is not enabled.
        /// </summary>
        public static string PaymentModeNotEnabled {
            get {
                return ResourceManager.GetString("PaymentModeNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is already registered with us.
        /// </summary>
        public static string PhoneAlreadyRegistered {
            get {
                return ResourceManager.GetString("PhoneAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phone Number is not registered with us. Please try again!.
        /// </summary>
        public static string PhoneNotRegistered {
            get {
                return ResourceManager.GetString("PhoneNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN:   {0}.
        /// </summary>
        public static string PinDisplay {
            get {
                return ResourceManager.GetString("PinDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be greater than 0.
        /// </summary>
        public static string PositiveAmountWarning {
            get {
                return ResourceManager.GetString("PositiveAmountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;0&apos; to go back.
        /// </summary>
        public static string PressBackButtonInfo {
            get {
                return ResourceManager.GetString("PressBackButtonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile update failed.
        /// </summary>
        public static string ProfileUpdateFailure {
            get {
                return ResourceManager.GetString("ProfileUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        public static string ProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase failed.
        /// </summary>
        public static string PurchaseFailure {
            get {
                return ResourceManager.GetString("PurchaseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase successful.
        /// </summary>
        public static string PurchaseSuccess {
            get {
                return ResourceManager.GetString("PurchaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter Password.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to reset pin failed. Please try again.
        /// </summary>
        public static string ResetPinFailure {
            get {
                return ResourceManager.GetString("ResetPinFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin reset successful.
        /// </summary>
        public static string ResetPinSuccess {
            get {
                return ResourceManager.GetString("ResetPinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in signing up. Please try again..
        /// </summary>
        public static string SignupFailure {
            get {
                return ResourceManager.GetString("SignupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup successful.
        /// </summary>
        public static string SignupSuccess {
            get {
                return ResourceManager.GetString("SignupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number to transfer.
        /// </summary>
        public static string TransferAccountNumber {
            get {
                return ResourceManager.GetString("TransferAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer unsuccessful.
        /// </summary>
        public static string TransferFailure {
            get {
                return ResourceManager.GetString("TransferFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of Rs.{0} is successful.
        /// </summary>
        public static string TransferSuccess {
            get {
                return ResourceManager.GetString("TransferSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw unsuccessful.
        /// </summary>
        public static string WithdrawFailure {
            get {
                return ResourceManager.GetString("WithdrawFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw of Rs.{0} is successful.
        /// </summary>
        public static string WithdrawSuccess {
            get {
                return ResourceManager.GetString("WithdrawSuccess", resourceCulture);
            }
        }
    }
}
